name: sushiland
description: A plant care mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  intl: ^0.18.1
  image_picker: ^1.0.7
  http: ^1.2.0
  image: ^4.1.7
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
